tfServing:
  name: fn-serving
  internalPort: 8500
  externalPort: 8500
  image: 
    name: jsphweid/fn_serving_base_gpu
    tag: latest

torchServe:
  name: fn-serving-torchserve
  inferencePort: 8080
  managementPort: 8081
  metricsPort: 8082
  grpcInferencePort: 7070
  image: 
    name: jsphweid/fn_torchserve_gpu
    tag: latest

grpc:
  name: fn-python-grpc
  internalPort: 50051
  externalPort: 5000
  image: 
    name: jsphweid/fn_py_grpc
    tag: latest

gql:
  name: fn-gql
  internalPort: 4000
  externalPort: 8080
  image: 
    name: jsphweid/fn_gql
    tag: latest

