apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fn-gql-ingress
spec:
  rules:
  - http:
      paths:
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.gql.name }}-service
            port:
              number: {{ .Values.gql.externalPort }}
